# Generated by Django 6.0.3 on 2026-04-04 03:26

import django.db.models.deletion
import keel.security.scanning
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harbor_core', '0001_initial'),
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('project_title', models.CharField(max_length=500)),
                ('project_description', models.TextField()),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount of funding requested', max_digits=15)),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('match_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Proposed matching contribution amount', max_digits=15, null=True)),
                ('match_description', models.TextField(blank=True, default='', help_text='Description of matching funds or in-kind contributions')),
                ('version', models.IntegerField(default=1)),
                ('version_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('grant_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='grants.grantprogram')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='harbor_core.organization')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('claimed', 'Self-Claimed'), ('manager_assigned', 'Manager Assigned')], default='claimed', max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reassigned', 'Reassigned')], default='assigned', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='applications.application')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The manager who made this assignment (null if self-claimed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Assignment',
                'verbose_name_plural': 'Application Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_internal', models.BooleanField(default=False, help_text='If True, this comment is visible only to staff reviewers')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='applications.application')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Comment',
                'verbose_name_plural': 'Application Comments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='applications/docs/', validators=[keel.security.scanning.FileSecurityValidator()])),
                ('document_type', models.CharField(choices=[('narrative', 'Project Narrative'), ('budget', 'Budget'), ('budget_justification', 'Budget Justification'), ('letters_of_support', 'Letters of Support'), ('resumes', 'Resumes / CVs'), ('organizational_chart', 'Organizational Chart'), ('audit_report', 'Audit Report'), ('tax_exempt_letter', 'Tax-Exempt Determination Letter'), ('other', 'Other')], default='other', max_length=25)),
                ('version_number', models.IntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_application_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'ordering': ['document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Status History',
                'verbose_name_plural': 'Application Status Histories',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='applications/staff_docs/', validators=[keel.security.scanning.FileSecurityValidator()])),
                ('document_type', models.CharField(choices=[('verification', 'Verification Document'), ('background_check', 'Background Check'), ('due_diligence', 'Due Diligence Memo'), ('reference_check', 'Reference Check'), ('site_visit', 'Site Visit Report'), ('legal_review', 'Legal Review'), ('financial_review', 'Financial Review'), ('other', 'Other')], default='other', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_documents', to='applications.application')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_staff_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Document',
                'verbose_name_plural': 'Staff Documents',
                'ordering': ['document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComplianceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('sam_registration', 'SAM Registration Active'), ('tax_exempt', 'Tax-Exempt Status Verified'), ('audit_clearance', 'Audit Clearance'), ('debarment_check', 'Debarment / Suspension Check'), ('budget_review', 'Budget Review Complete'), ('narrative_review', 'Narrative Review Complete'), ('insurance_verified', 'Insurance Verification'), ('match_verified', 'Match Funds Verified'), ('conflict_of_interest', 'Conflict of Interest Check'), ('eligibility_confirmed', 'Eligibility Confirmed')], max_length=30)),
                ('label', models.CharField(help_text='Human-readable description of the compliance requirement', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Staff notes about this compliance item')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this item must be verified before approval')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_items', to='applications.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_compliance_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Compliance Item',
                'verbose_name_plural': 'Application Compliance Items',
                'ordering': ['item_type'],
                'unique_together': {('application', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=255)),
                ('section_order', models.IntegerField(default=0)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Flexible form data stored as JSON')),
                ('is_complete', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='applications.application')),
            ],
            options={
                'verbose_name': 'Application Section',
                'verbose_name_plural': 'Application Sections',
                'ordering': ['section_order'],
                'unique_together': {('application', 'section_order')},
            },
        ),
    ]
