# Generated by Django 6.0.3 on 2026-05-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_applicationattachment_file'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('harbor_core', '0007_auditlog_deep_link_snapshot_auditlog_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(db_index=True, help_text='Dotted snake_case identifier from the verb catalog (e.g. "collab.added", "signing.signed", "interaction.logged").', max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64, null=True)),
                ('action_id', models.CharField(blank=True, max_length=64, null=True)),
                ('visibility', models.CharField(choices=[('collaborators', 'Collaborators'), ('agency', 'Agency-wide'), ('staff', 'Internal staff only'), ('public', 'Public on this record'), ('stub', 'Cross-zone stub (actor + verb + date only)')], db_index=True, default='collaborators', max_length=16)),
                ('source_product', models.CharField(db_index=True, help_text='Short identifier for the product that emitted this row (helm, manifest, beacon, etc). Comes from settings.KEEL_PRODUCT_CODE.', max_length=32)),
                ('deep_link', models.URLField(blank=True, default='', help_text='Absolute URL of the target, frozen at write time. Used for cross-product navigation in Helm aggregator. Computed from target.get_absolute_url() prefixed with KEEL_PRODUCT_BASE_URL at write time.', max_length=512)),
                ('source_label', models.CharField(blank=True, default='', help_text='Human-readable summary, e.g. "added Alice as Lead". Renders in feed UI.', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form context: from/to status for transitions, signer email for sign events, role for collaborator changes, zone for Beacon interactions, etc. Distinct from audit.changes which carries the snapshot of audited fields.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, help_text='Denormalized FK to Application for fast detail-page queries. Backfilled from target on save when target IS an Application.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='applications.application')),
                ('audit_ref', models.ForeignKey(blank=True, help_text='Back-pointer to the AuditLog row that triggered (Track A) or accompanied (Track B) this activity. PROTECT because deleting an audit row would orphan the activity. Track-A duplicate prevention uses the unique constraint below.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='harbor_core.auditlog')),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['target_ct', 'target_id', '-created_at'], name='applic_activity_tgt_ix'), models.Index(fields=['actor', '-created_at'], name='applic_activity_act_ix'), models.Index(fields=['verb', '-created_at'], name='applic_activity_verb_ix'), models.Index(fields=['application', '-created_at'], name='applic_activity_app_ix')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('audit_ref__isnull', False)), fields=('audit_ref',), name='applic_activity_aud_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(blank=True, help_text='Null with target_ct set = "all records of this type". Both null = global watcher (rare).', max_length=64, null=True)),
                ('filter_predicate', models.JSONField(blank=True, help_text='Dotted-path keys against activity.metadata or target fields. Exact-equal values only in v1 (no operators). Example: {"metadata.from_status": "draft", "target.agency.abbr": "DEC"}.', null=True)),
                ('notify_verbs', models.JSONField(blank=True, default=list, help_text='List of verb strings. Empty = match all visible verbs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_ct', models.ForeignKey(blank=True, help_text='Null = match any content type (rare; usually only for staff watchers).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'target_ct', 'target_id'], name='applic_watcher_ut_ix')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('target_ct__isnull', False), ('target_id__isnull', False)), fields=('user', 'target_ct', 'target_id'), name='applic_watcher_uniq')],
            },
        ),
    ]
