# Generated by Django 5.2.13 on 2026-05-14 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_activity_watcher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcomment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
