# Generated by Django 6.0.3 on 2026-05-18 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationcomment_mentions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='Set for external invites.', max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('contributor', 'Contributor'), ('reviewer', 'Reviewer'), ('observer', 'Observer')], default='contributor', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_on_notes', models.BooleanField(default=True)),
                ('notify_on_status', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='applications.application')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_invited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Internal user; null for external email invites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Collaborator',
                'verbose_name_plural': 'Application Collaborators',
                'ordering': ['-invited_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('application', 'user'), name='unique_application_collaborator_user'), models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('email', ''), _negated=True)), fields=('application', 'email'), name='unique_application_collaborator_email')],
            },
        ),
    ]
