# Generated by Django 6.0.3 on 2026-04-04 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('department_code', models.CharField(blank=True, max_length=8, verbose_name='State ERP Department Code')),
                ('fund_code', models.CharField(blank=True, max_length=5, verbose_name='Fund Code')),
                ('program_code', models.CharField(blank=True, max_length=5, verbose_name='Program Code')),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('can_be_grantee', models.BooleanField(default=False, help_text='Can this agency receive grants from other agencies?')),
                ('can_be_grantor', models.BooleanField(default=True, help_text='Can this agency award grants?')),
                ('is_active', models.BooleanField(default=True)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('municipality', 'Municipality'), ('nonprofit', 'Nonprofit'), ('business', 'Business'), ('individual', 'Individual'), ('tribal', 'Tribal Nation'), ('educational', 'Educational Institution'), ('other', 'Other')], default='nonprofit', max_length=20, verbose_name='Organization Type')),
                ('duns_number', models.CharField(blank=True, max_length=13, verbose_name='DUNS Number')),
                ('uei_number', models.CharField(blank=True, max_length=12, verbose_name='UEI Number')),
                ('ein', models.CharField(blank=True, max_length=10, verbose_name='EIN')),
                ('sam_registered', models.BooleanField(default=False, verbose_name='SAM Registered')),
                ('sam_expiration', models.DateField(blank=True, null=True, verbose_name='SAM Expiration Date')),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='CT', max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_high_priority', models.BooleanField(default=False, help_text='Manually flagged as high-priority for assigned contact tracking.', verbose_name='High Priority')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HarborProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthropic_api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Anthropic API Key')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harbor_users', to='harbor_core.agency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harbor_profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harbor_users', to='harbor_core.organization')),
            ],
            options={
                'verbose_name': 'Harbor Profile',
                'verbose_name_plural': 'Harbor Profiles',
            },
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_contact', to='harbor_core.organization')),
            ],
            options={
                'verbose_name': 'Organization Contact',
                'verbose_name_plural': 'Organization Contacts',
            },
        ),
        migrations.CreateModel(
            name='ArchivedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('application', 'Application'), ('award', 'Award'), ('drawdown', 'Drawdown Request'), ('report', 'Report'), ('audit_log', 'Audit Log'), ('transaction', 'Transaction')], max_length=20)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_description', models.TextField(blank=True)),
                ('retention_policy', models.CharField(choices=[('standard', 'Standard (7 years)'), ('extended', 'Extended (10 years)'), ('permanent', 'Permanent'), ('federal', 'Federal Requirement (3 years post-closeout)')], default='standard', max_length=15)),
                ('original_created_at', models.DateTimeField(help_text='When the original record was created')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('retention_expires_at', models.DateTimeField(blank=True, help_text='When this archived record can be permanently deleted', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Preserved metadata from the archived record')),
                ('is_purged', models.BooleanField(default=False, help_text='Whether the original record has been purged from the system')),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Record',
                'verbose_name_plural': 'Archived Records',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_archive_entity'), models.Index(fields=['retention_expires_at'], name='idx_archive_expiry')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('export', 'Export'), ('view', 'View'), ('login_failed', 'Login Failed'), ('security_event', 'Security Event')], max_length=25)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'abstract': False,
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_entity'), models.Index(fields=['user', 'timestamp'], name='idx_audit_user_ts')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='idx_notif_recip_read')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['recipient', 'notification_type', '-created_at'], name='core_notifi_recipie_f4ed05_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(help_text='Registry key of the notification type.', max_length=100)),
                ('channel_in_app', models.BooleanField(default=True, verbose_name='In-app notifications')),
                ('channel_email', models.BooleanField(default=True, verbose_name='Email notifications')),
                ('channel_sms', models.BooleanField(default=False, verbose_name='SMS notifications')),
                ('is_muted', models.BooleanField(default=False, help_text='Completely disable this notification type.', verbose_name='Mute this notification')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'ordering': ['notification_type'],
                'abstract': False,
                'unique_together': {('user', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='harbor_core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Claim',
                'verbose_name_plural': 'Organization Claims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_claim_status_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'user'), name='unique_pending_claim_per_user_org')],
            },
        ),
    ]
