# Generated by Django 5.2.12 on 2026-04-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harbor_core', '0003_notificationpreference_channel_boswell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harborprofile',
            name='anthropic_api_key',
        ),
    ]
