# Generated by Django 6.0.3 on 2026-04-26 21:36
#
# State-only migration. Production DBs already have these tables under
# the harbor_core_* names (renamed by an out-of-band fixup) and the
# index already carries the new name; running the table/index renames
# again would error with "relation does not exist". This migration just
# brings Django's migration state in line with reality.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor_core', '0005_drop_orphan_bounty_tables'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='notificationlog',
                    new_name='harbor_core_recipie_4d047e_idx',
                    old_name='core_notifi_recipie_f4ed05_idx',
                ),
                migrations.AlterField(
                    model_name='auditlog',
                    name='action',
                    field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('export', 'Export'), ('view', 'View'), ('login_failed', 'Login Failed'), ('security_event', 'Security Event'), ('archive', 'Archive'), ('unarchive', 'Unarchive')], max_length=25),
                ),
                migrations.AlterModelTable(name='agency', table='harbor_core_agency'),
                migrations.AlterModelTable(name='archivedrecord', table='harbor_core_archivedrecord'),
                migrations.AlterModelTable(name='auditlog', table='harbor_core_auditlog'),
                migrations.AlterModelTable(name='harborprofile', table='harbor_core_harborprofile'),
                migrations.AlterModelTable(name='notification', table='harbor_core_notification'),
                migrations.AlterModelTable(name='notificationlog', table='harbor_core_notificationlog'),
                migrations.AlterModelTable(name='notificationpreference', table='harbor_core_notificationpreference'),
                migrations.AlterModelTable(name='organization', table='harbor_core_organization'),
                migrations.AlterModelTable(name='organizationclaim', table='harbor_core_organizationclaim'),
                migrations.AlterModelTable(name='organizationcontact', table='harbor_core_organizationcontact'),
            ],
        ),
    ]
