# Generated by Django 6.0.2 on 2026-03-18 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_agency_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_high_priority',
            field=models.BooleanField(default=False, help_text='Manually flagged as high-priority for assigned contact tracking.', verbose_name='High Priority'),
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_contact', to='core.organization')),
            ],
            options={
                'verbose_name': 'Organization Contact',
                'verbose_name_plural': 'Organization Contacts',
            },
        ),
        migrations.CreateModel(
            name='OrganizationClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Claim',
                'verbose_name_plural': 'Organization Claims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_claim_status_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'user'), name='unique_pending_claim_per_user_org')],
            },
        ),
    ]
