# Generated by Django 6.0.3 on 2026-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor_core', '0006_rename_core_notifi_recipie_f4ed05_idx_harbor_core_recipie_4d047e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='deep_link_snapshot',
            field=models.CharField(blank=True, default='', help_text='Absolute URL of the audited target captured at audit-write time. Used by keel.activity promotion rules to avoid stale URLs when backfilling or replaying audit history through the activity layer.', max_length=256),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Free-form context for explicit audit emission (record_activity, manual log_audit calls with structured info). Distinct from changes which auto-signal populates with field snapshots.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('export', 'Export'), ('view', 'View'), ('login_failed', 'Login Failed'), ('security_event', 'Security Event'), ('archive', 'Archive'), ('unarchive', 'Unarchive'), ('role_grant_denied', 'Role Grant Denied'), ('username_change', 'Username Change'), ('email_change', 'Email Change'), ('avatar_change', 'Avatar Change')], max_length=25),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of audited field values at save time (auto-signal pathway). Empty for explicit log_audit() / record_activity() calls — they use the metadata field for free-form context instead. changes retains diff/snapshot semantics that downstream tooling depends on.'),
        ),
    ]
