# Generated by Django 6.0.2 on 2026-03-20 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_organization_claims_and_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('export', 'Export'), ('view', 'View'), ('login_failed', 'Login Failed'), ('security_event', 'Security Event')], max_length=25),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
