# Generated by Django 6.0.3 on 2026-04-04 03:26

import django.db.models.deletion
import keel.security.scanning
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('private', 'Private'), ('mixed', 'Mixed')], default='state', max_length=20)),
                ('cfda_number', models.CharField(blank=True, default='', help_text='Catalog of Federal Domestic Assistance number (federal sources only)', max_length=20)),
                ('federal_agency', models.CharField(blank=True, default='', help_text='Originating federal agency, if applicable', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funding Source',
                'verbose_name_plural': 'Funding Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FederalOpportunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opportunity_id', models.CharField(help_text='Unique identifier from Grants.gov', max_length=64, unique=True)),
                ('opportunity_number', models.CharField(blank=True, default='', help_text='Opportunity number / NOFO number', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('agency_name', models.CharField(blank=True, default='', max_length=255)),
                ('agency_code', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', help_text='Funding category / opportunity category', max_length=255)),
                ('funding_instrument', models.CharField(choices=[('grant', 'Grant'), ('cooperative_agreement', 'Cooperative Agreement'), ('procurement_contract', 'Procurement Contract'), ('other', 'Other')], default='grant', max_length=30)),
                ('cfda_numbers', models.JSONField(blank=True, default=list, help_text='List of CFDA/Assistance Listing numbers')),
                ('award_floor', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum award amount', max_digits=15, null=True)),
                ('award_ceiling', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum award amount', max_digits=15, null=True)),
                ('expected_awards', models.IntegerField(blank=True, help_text='Expected number of awards', null=True)),
                ('total_funding', models.DecimalField(blank=True, decimal_places=2, help_text='Total estimated funding', max_digits=15, null=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('archive_date', models.DateField(blank=True, null=True)),
                ('opportunity_status', models.CharField(choices=[('posted', 'Posted'), ('closed', 'Closed'), ('archived', 'Archived'), ('forecasted', 'Forecasted')], default='posted', max_length=15)),
                ('applicant_types', models.JSONField(blank=True, default=list, help_text='List of eligible applicant types')),
                ('eligible_applicants', models.TextField(blank=True, default='', help_text='Additional eligibility text')),
                ('grants_gov_url', models.URLField(blank=True, default='', help_text='Link to the opportunity on Grants.gov', max_length=500)),
                ('synced_at', models.DateTimeField(auto_now_add=True, help_text='When this record was last synced from Grants.gov')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full API response for this opportunity')),
                ('funding_source', models.ForeignKey(blank=True, help_text='Linked FundingSource when a GrantProgram is created from this opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federal_opportunities', to='grants.fundingsource')),
            ],
            options={
                'verbose_name': 'Federal Opportunity',
                'verbose_name_plural': 'Federal Opportunities',
                'ordering': ['-post_date', '-close_date'],
            },
        ),
        migrations.CreateModel(
            name='GrantPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text='List of focus area keys from FocusArea choices')),
                ('eligible_org_types', models.JSONField(blank=True, default=list, help_text='List of organization type keys the user is interested in')),
                ('funding_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum funding amount of interest', max_digits=15, null=True)),
                ('funding_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum funding amount of interest', max_digits=15, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Describe your priorities, mission, or what you are looking for in your own words')),
                ('is_active', models.BooleanField(default=True, help_text='Whether AI matching is enabled for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grant_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grant Preference',
                'verbose_name_plural': 'Grant Preferences',
            },
        ),
        migrations.CreateModel(
            name='GrantProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('grant_type', models.CharField(choices=[('competitive', 'Competitive'), ('non_competitive', 'Non-Competitive'), ('formula', 'Formula'), ('continuation', 'Continuation'), ('other', 'Other')], default='competitive', max_length=20)),
                ('eligibility_criteria', models.TextField(blank=True, default='', help_text='Description of who may apply')),
                ('total_funding', models.DecimalField(decimal_places=2, help_text='Total funding available for this program', max_digits=15)),
                ('min_award', models.DecimalField(decimal_places=2, help_text='Minimum award amount', max_digits=15)),
                ('max_award', models.DecimalField(decimal_places=2, help_text='Maximum award amount', max_digits=15)),
                ('match_required', models.BooleanField(default=False, help_text='Whether a matching contribution is required')),
                ('match_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Required match as a percentage (e.g. 25.00 for 25%)', max_digits=5, null=True)),
                ('fiscal_year', models.CharField(help_text='e.g. 2025-2026', max_length=9)),
                ('multi_year', models.BooleanField(default=False, help_text='Whether awards span multiple fiscal years')),
                ('duration_months', models.IntegerField(help_text='Grant period duration in months')),
                ('application_deadline', models.DateTimeField(db_index=True)),
                ('posting_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('accepting_applications', 'Accepting Applications'), ('under_review', 'Under Review'), ('awards_pending', 'Awards Pending'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=25)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('application_form_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration defining custom application form sections and fields per program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_programs', to='core.agency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_grant_programs', to=settings.AUTH_USER_MODEL)),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_programs', to='grants.fundingsource')),
            ],
            options={
                'verbose_name': 'Grant Program',
                'verbose_name_plural': 'Grant Programs',
                'ordering': ['-posting_date'],
            },
        ),
        migrations.CreateModel(
            name='GrantProgramDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='grant_programs/docs/', validators=[keel.security.scanning.FileSecurityValidator()])),
                ('document_type', models.CharField(choices=[('nofa', 'Notice of Funding Availability'), ('guidelines', 'Program Guidelines'), ('budget_template', 'Budget Template'), ('application_form', 'Application Form'), ('faq', 'FAQ'), ('amendment', 'Amendment'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grants.grantprogram')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_grant_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grant Program Document',
                'verbose_name_plural': 'Grant Program Documents',
                'ordering': ['document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('federal', 'Federal'), ('state', 'State')], max_length=10)),
                ('relevance_score', models.IntegerField(help_text='AI relevance score from 0 to 100')),
                ('explanation', models.TextField(blank=True, default='', help_text='AI-generated explanation of why this is a match')),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('saved', 'Saved'), ('dismissed', 'Dismissed')], default='new', max_length=10)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], default='', help_text='User feedback on this recommendation', max_length=10)),
                ('feedback_reason', models.CharField(blank=True, choices=[('wrong_focus', 'Wrong focus area'), ('budget_too_large', 'Budget too large'), ('budget_too_small', 'Budget too small'), ('already_aware', 'Already aware of this'), ('not_eligible', 'Not eligible'), ('not_relevant', 'Not relevant to our mission'), ('other', 'Other')], default='', help_text='Reason for negative feedback', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('federal_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='grants.federalopportunity')),
                ('grant_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='grants.grantprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity Match',
                'verbose_name_plural': 'Opportunity Matches',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest_level', models.CharField(choices=[('watching', 'Watching'), ('interested', 'Interested'), ('planning_to_apply', 'Planning to Apply')], default='watching', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='grants.grantprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Program',
                'verbose_name_plural': 'Saved Programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackedOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('preparing', 'Preparing Application'), ('applied', 'Applied'), ('awarded', 'Awarded'), ('declined', 'Declined')], default='watching', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('federal_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_records', to='grants.federalopportunity')),
                ('grant_program', models.ForeignKey(blank=True, help_text='Internal Grant Program linked to this federal opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_federal_opportunities', to='grants.grantprogram')),
                ('tracked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracked Opportunity',
                'verbose_name_plural': 'Tracked Opportunities',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', help_text='Email for external collaborators not yet in Harbor', max_length=254)),
                ('name', models.CharField(blank=True, default='', help_text='Name for external collaborators', max_length=255)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('contributor', 'Contributor'), ('reviewer', 'Reviewer'), ('observer', 'Observer')], default='contributor', max_length=15)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federal_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Internal Harbor user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federal_collaborations', to=settings.AUTH_USER_MODEL)),
                ('tracked_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='grants.trackedopportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Collaborator',
                'verbose_name_plural': 'Opportunity Collaborators',
                'ordering': ['role', '-invited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='federalopportunity',
            index=models.Index(fields=['opportunity_status', 'close_date'], name='idx_fedopp_status_close'),
        ),
        migrations.AddIndex(
            model_name='federalopportunity',
            index=models.Index(fields=['agency_code'], name='idx_fedopp_agency'),
        ),
        migrations.AddIndex(
            model_name='opportunitymatch',
            index=models.Index(fields=['user', 'status'], name='idx_oppmatch_user_status'),
        ),
        migrations.AddConstraint(
            model_name='opportunitymatch',
            constraint=models.UniqueConstraint(condition=models.Q(('federal_opportunity__isnull', False)), fields=('user', 'federal_opportunity'), name='unique_user_federal_match'),
        ),
        migrations.AddConstraint(
            model_name='opportunitymatch',
            constraint=models.UniqueConstraint(condition=models.Q(('grant_program__isnull', False)), fields=('user', 'grant_program'), name='unique_user_state_match'),
        ),
        migrations.AlterUniqueTogether(
            name='savedprogram',
            unique_together={('grant_program', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='trackedopportunity',
            unique_together={('federal_opportunity', 'tracked_by')},
        ),
    ]
