# Generated by Django 6.0.3 on 2026-04-22 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitycollaborator',
            options={'ordering': ['-invited_at'], 'verbose_name': 'Opportunity Collaborator', 'verbose_name_plural': 'Opportunity Collaborators'},
        ),
        migrations.AddField(
            model_name='opportunitycollaborator',
            name='notify_on_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opportunitycollaborator',
            name='notify_on_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='email',
            field=models.EmailField(blank=True, help_text='Set for external invites.', max_length=254),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead'), ('contributor', 'Contributor'), ('reviewer', 'Reviewer'), ('observer', 'Observer')], default='contributor', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Internal user; null for external email invites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
