# Generated by Django 6.0.2 on 2026-03-20 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0009_alter_grantprogram_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email for external collaborators not yet in Harbor', max_length=254),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Internal Harbor user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federal_collaborations', to=settings.AUTH_USER_MODEL),
        ),
    ]
