# Generated by Django 6.0.3 on 2026-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_notificationpreference_channel_boswell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('export', 'Export'), ('view', 'View'), ('login_failed', 'Login Failed'), ('security_event', 'Security Event'), ('archive', 'Archive'), ('unarchive', 'Unarchive')], max_length=25),
        ),
    ]
