# Generated by Django 6.0.3 on 2026-04-04 03:26

import django.db.models.deletion
import keel.security.scanning
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('harbor_core', '0001_initial'),
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('award_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('executed', 'Executed'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('terms_and_conditions', models.TextField()),
                ('special_conditions', models.TextField(blank=True)),
                ('requires_match', models.BooleanField(default=False)),
                ('match_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='harbor_core.agency')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='applications.application')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_awards', to=settings.AUTH_USER_MODEL)),
                ('grant_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='grants.grantprogram')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='harbor_core.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AwardAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.IntegerField()),
                ('amendment_type', models.CharField(choices=[('budget_modification', 'Budget Modification'), ('time_extension', 'Time Extension'), ('scope_change', 'Scope Change'), ('personnel_change', 'Personnel Change'), ('other', 'Other')], max_length=25)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(default=dict)),
                ('new_value', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied')], default='draft', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_amendments', to=settings.AUTH_USER_MODEL)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='awards.award')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_amendments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Award Amendment',
                'verbose_name_plural': 'Award Amendments',
                'ordering': ['award', 'amendment_number'],
            },
        ),
        migrations.CreateModel(
            name='AwardDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='awards/docs/', validators=[keel.security.scanning.FileSecurityValidator()])),
                ('document_type', models.CharField(choices=[('agreement', 'Agreement'), ('amendment', 'Amendment'), ('correspondence', 'Correspondence'), ('report', 'Report'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='awards.award')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_award_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Award Document',
                'verbose_name_plural': 'Award Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('output', 'Output'), ('outcome', 'Outcome'), ('efficiency', 'Efficiency')], default='output', max_length=15)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unit_of_measure', models.CharField(help_text='e.g. people served, jobs created', max_length=100)),
                ('reporting_period', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='awards.award')),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['award', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('envelope_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('signed', 'Signed'), ('declined', 'Declined'), ('voided', 'Voided')], default='sent', max_length=20)),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='awards/signed/', validators=[keel.security.scanning.FileSecurityValidator()])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='awards.award')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature Request',
                'verbose_name_plural': 'Signature Requests',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SubRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('sub_award_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scope_of_work', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=15)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('monitoring_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_recipients', to='awards.award')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_recipient_awards', to='harbor_core.organization')),
            ],
            options={
                'verbose_name': 'Sub-Recipient',
                'verbose_name_plural': 'Sub-Recipients',
                'ordering': ['organization__name'],
            },
        ),
    ]
