# Generated by Django 6.0.3 on 2026-04-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_consolidate_award_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='fund_source',
            field=models.CharField(blank=True, choices=[('arpa', 'ARPA — American Rescue Plan Act'), ('iija', 'IIJA — Infrastructure Investment and Jobs Act'), ('ira', 'IRA — Inflation Reduction Act'), ('bead', 'BEAD — Broadband Equity, Access, and Deployment'), ('slcgp', 'SLCGP — State and Local Cybersecurity Grant'), ('cdbg', 'CDBG — Community Development Block Grant'), ('go_bond', 'General Obligation Bond'), ('revenue_bond', 'Revenue Bond'), ('state_match', 'State Match'), ('local_match', 'Local Match'), ('general_fund', 'General Fund')], db_index=True, help_text='Federal/state fund source. Used by Helm to join Harbor drawdown data into its CIP fund-source rollup. Leave blank when not applicable.', max_length=20),
        ),
    ]
